services:
  backend:
    build: ./backend
    volumes:
      - ./.env:/app/.env
      - ./kalshi-private.key:/app/kalshi-private.key
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
